### ISSUE TITLE
Use plone.stringinterp

### ISSUE THREAD

**Issue by puittenbroek** [RedTurtle/collective.contentrules.mailfromfield#2]
Hi,

Your product is very nice, but is lacking some easy to use string replacement utilities.
[plone.stringinterp](https://github.com/plone/plone.stringinterp) provides this, as used in [plone.app.contentrules.actions.mail](https://github.com/plone/plone.app.contentrules/blob/master/plone/app/contentrules/actions/mail.py#L99)

You can easily provided new replacements such as you do with your mapping.

**Comment by cekk** [comment]
I know it's late, but 1.0.0 version has support to stringinterp ;)
